name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest tests/

      - name: Build Docker image
        run: docker build -t smart-log-analyzer .

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: smartloacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag smart-log-analyzer smartloacr.azurecr.io/smart-log-analyzer:latest
          docker push smartloacr.azurecr.io/smart-log-analyzer:latest

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: smart-log-analyzer
          images: smartloacr.azurecr.io/smart-log-analyzer:latest
